### ISSUE TITLE
container logs are not logged if the container fails the healthcheck

### ISSUE THREAD

**Issue by dcermak** [dcermak/pytest_container#138]

**Comment by danishprakash** [comment]
Is this a `good-first-issue` candidate?

**Comment by dcermak** [comment]
Indeed. The issue is rather simple, when the container fails the healthcheck, then an exception is thrown inside of this call: https://github.com/dcermak/pytest_container/blob/ab4bea87724afe3eb7567d62990833c819ba9c85/pytest_container/plugin.py#L107

The container logs logging (what a mouthful…) happens a few lines below though. So a well placed try - finally should solve this issue.
