### ISSUE TITLE
Add wait_for_port function

### ISSUE THREAD

**Issue by nunofernandes** [dcermak/pytest_container#143]
Hello,

I'm using [conu](https://conu.readthedocs.io/en/latest/index.html) to test my container but would like to change to pytest_container as it suports podman.

One function that it has available is [wait_for_port](https://conu.readthedocs.io/en/latest/reference/docker_container.html#conu.DockerContainer.wait_for_port) that I use extensively and would be awesome if `pytest_container` also had support for it.
I know that would be achievable using HEALTHCHECK but I think it's better to have that `wait_for_port`  supported. Could that be implemented?

Thanks,

**Comment by grisu48** [comment]
This feature makes sense to have. Dan I would also expect that this comes in handy for new SUSE application image containers to avoid stupid race conditions.

:+1:

**Comment by dcermak** [comment]
I am afraid that sadly this feature cannot be implemented reliably in `pytest_container`. The big problem here is rootless podman. If you create a rootless container with podman, then podman will not be able to assign your container a IP address. Instead it will use a usermode network stack to bridge the network traffic. This also includes exposed ports. In practice that means that if you run: `podman run -p 8000:8000 some/image` then podman will open port 8000 on localhost. But that is really the only way how you can reach whatever is (or is not) inside the container. Now if you try to connect to port 8000 on localhost, that will always succeed even if the container is just running a shell or `sleep infinity`. Even sending data there does not help as you don't get an error if nothing is reading your data in the container…

So unless anyone has a good idea how to solve this problem, I'll close this issue for now.

My current WIP (and quite sorry) state is in the https://github.com/dcermak/pytest_container/tree/port-timeout branch.

**Comment by nunofernandes** [comment]
I just watched https://www.youtube.com/watch?v=S30Kj135-Kc with the title "Rootful networking with rootless podman containers - DevConf.CZ 2023"... Also more information at https://github.com/neverpanic/podman-rootful-network. It should work with `uidmap` option and podman 4.5.0.
