### ISSUE TITLE
No possibility to pass command or args to `podman run`

### ISSUE THREAD

**Issue by AdrianVollmer** [dcermak/pytest_container#168]
Hi, please correct me if I'm wrong and misunderstanding something.

According to the man page (`man podman-run(1)`), `podman run` takes these arguments:

```
 podman run [options] image [command [arg ...]]
```

However, the [docs](https://dcermak.github.io/pytest_container/api.html#pytest_container.container.ContainerBase) say that we can only specify `extra_launch_args`, which will be inserted somewhere between `run` and `<image>`. Looking at the [source](https://github.com/dcermak/pytest_container/blob/main/pytest_container/container.py#L545), it becomes clear that there is no way to append extra arguments at the end of the launch command.

I believe that `ContainerBase` should take another keyword argument called `extra_command` and/or `extra_command_args` or something that will be appended at the end after the image name.

My use case is that I want to use [this samba image](https://hub.docker.com/r/dperson/samba), which takes arguments at the end.

What do you think?

Thank you very much for your consideration.

**Comment by dcermak** [comment]
> I believe that `ContainerBase` should take another keyword argument called `extra_command` and/or `extra_command_args` or something that will be appended at the end after the image name.

Yes, that sounds reasonable. I simply haven't encountered this use case before.

> My use case is that I want to use [this samba image](https://hub.docker.com/r/dperson/samba), which takes arguments at the end.

side note: that image is **severely** outdated (last update is 3 years ago :scream:)

> 
> What do you think?
> 
> Thank you very much for your consideration.

This sounds good to me, I'll implement this. And thank you very much for using this library and providing feedback!

**Comment by AdrianVollmer** [comment]
Good point. I should probably use another image entirely. Thanks for the hint!
