### ISSUE TITLE
Option for not pulling container images

### ISSUE THREAD

**Issue by martinpitt** [dcermak/pytest_container#187]
Each test run currently tries very hard to pull the latest and greatest images from the container registry. This is unnerving when developing/iterating, as this takes about 10s for the four container images which are involved in my test. The actual test only takes about 3 seconds afterwards.

While this may be a good default, could you please add an option to *not* explicitly pull the `Container(url=...)` image? `podman run` will auto-pull it if it doesn't exist, but if it already exists locally it will just use that. This is *much* faster.

Thanks!

**Comment by dcermak** [comment]
This makes sense, would you prefer a global switch or a per-container switch?

**Comment by martinpitt** [comment]
:thinking: I suppose a global one would make a bit more sense. Ideally this would rather be something that you can switch without having to change the code, perhaps an env variable? I'm still a pytest beginner, but perhaps [pytest.Config](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.Config) supports this somehow? (Although I didn't find anything in `pytest --help` that resembles free-style config options to the test).

If that's impractical or inelegant, a per-`Container` one would work as well. Often you have a couple of auxiliary containers (in my case, RabbitMQ and minio) which aren't the actual test subject, so their version  is not super-crucial. 

Thanks!

**Comment by martinpitt** [comment]
For those following along: I found a nice hack. After instantiating `Container(), set `my_container._is_local = True`. That will short-circuit the `pull_container()` call in `prepare_container()`. podman run will still pull missing images by itself.

Et voilà, I can do test development in a train without (or only very little) internet :rocket:

**Comment by dcermak** [comment]
> 🤔 I suppose a global one would make a bit more sense. Ideally this would rather be something that you can switch without having to change the code, perhaps an env variable? I'm still a pytest beginner, but perhaps [pytest.Config](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.Config) supports this somehow? (Although I didn't find anything in `pytest --help` that resembles free-style config options to the test).
> 
> If that's impractical or inelegant, a per-`Container` one would work as well. Often you have a couple of auxiliary containers (in my case, RabbitMQ and minio) which aren't the actual test subject, so their version is not super-crucial.

The global switch via an environment variable turned out to be the simplest: https://github.com/dcermak/pytest_container/pull/189


> For those following along: I found a nice hack. After instantiating `Container()`, set `my_container._is_local = True`. That will short-circuit the `pull_container()` call in `prepare_container()`. podman run will still pull missing images by itself.
> 
> Et voilà, I can do test development in a train without (or only very little) internet 🚀

Do note that this is an internal variable intended for images that are only available in the local container storage (see https://dcermak.github.io/pytest_container/usage.html#testing-local-images). The intended usage of this flag is to define your containers as:
```Python
ctr = Container(url="container-storage:quay.io/minio/minio")
```
But this would fail, if the container is not already present in your container storage. I originally added this feature to be able to run the BCI testsuite against images that have been build locally and are not on some registry, but never really used it extensively, so probably there be :dragon: .

**Comment by martinpitt** [comment]
Excellent, thank you!

> Do note that this is an internal variable

Yes, that's why it has a big "HACK" comment. I don't intend to actually land this, that's just while I develop it.
