### ISSUE TITLE
API for running command in container without stdout/err capturing

### ISSUE THREAD

**Issue by martinpitt** [dcermak/pytest_container#188]
The only documented way to run a command in a container is  the  `Container.connection.run()` or friends like `.check_output()`, i.e. the [testinfra API](https://testinfra.readthedocs.io/en/latest/modules.html#testinfra.host.Host.run).

But this is highly annoying for debugging: `run()` (all other methods are based on that) unconditionally captures stderr, so if anything fails, the `pytest` output is useless. It would be much nicer to have a convenient way to not capture stderr there, but just let it go into pytest's stderr capturing, so that it gets shown on test failure.

Essentially something around
```py
subprocess.run(['podman', 'exec', '-i', my_container_data.container_id, '-', *args)
```

It *is* useful (for some cases) to capture stdout there to do assertions, so that should be a boolean option.

**Comment by martinpitt** [comment]
I added an implementation of this proposal in https://github.com/cockpit-project/cockpituous/commit/be515b0282f90cec59bbcd1df1c316101d1820d9

**Comment by dcermak** [comment]
Have you tried invoking pytest in verbose mode and enable logging? testinfra logs all command executions to the python logger, so they should be visible in the log. For the BCI testsuite we invoke `pytest` with `-vv` and that gives us e.g.:
```
------------------------------------------------------------- Captured log call --------------------------------------------------------------
DEBUG    testinfra:base.py:328 RUN CommandResult(backend=<testinfra.backend.local.LocalBackend object at 0x7f9818a54b90>, exit_status=0, command=b'podman run --rm registry.opensuse.org/devel/bci/sle-15-sp6/containerfile/bci/openjdk-devel:21', _stdout=b'|  Welcome to JShell -- Version 21.0.2\n|  For an introduction type: /help intro\n', _stderr=b'Mar 15, 2024 10:11:50 AM java.util.prefs.FileSystemPreferences$1 run\nINFO: Created user preferences directory.\n\njshell> ')
```

It's not super pretty, but has been good^:tm:  enough for us so far.

JFYI, you can also increase the verbosity of `pytest_container` itself: https://dcermak.github.io/pytest_container/usage.html#configuring-logging, then you'll also get the logs out of the container.

**Comment by martinpitt** [comment]
Ah thanks! Yes, `-vv`  works. It's rather hard to read, but at least it's there.

I tried
```
import pytest_container.logging

def pytest_configure(config):
    pytest_container.logging.set_internal_logging_level(20)
```

I tried both 20 and 0, but neither makes a difference in default `pytest` mode. The [API docs](https://dcermak.github.io/pytest_container/api.html#module-pytest_container.logging) isn't clear what this level actually means, or which strings can be given.

Anyway, thanks for the hints!

**Comment by martinpitt** [comment]
I think I'm going to keep my non-redirected implementations, though. It's really nice to be able to run`pytest -s` and see the ouput in real time, especially for long-running and complicated tests.

**Comment by dcermak** [comment]
> I think I'm going to keep my non-redirected implementations, though. It's really nice to be able to run `pytest -s` and see the output in real time, especially for long-running and complicated tests.

Sure, makes sense! However, I personally don't see this as such a huge pain point and do not want to implement this in pytest_container.
